project:
  type: website
  output-dir: docs

website:
  title: "Test2Dalarna"
  navbar:
    left:
      - href: index.qmd
        text: Dalastrategin
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

